on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt update
    - run: sudo apt install -y graphviz
    - run: make
    - uses: actions/upload-artifact@v3
      with:
        name: tree
        path: tree.pdf
